"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class CommandType(object):
    __slots__ = [ "value" ]
    None = 0
    Start_Record = 1
    Save_Record = 2
    Discard_Record = 3
    _packed_fingerprint = struct.pack(">Q", 0x8496f4a66b004f42)

    def __init__ (self, value):
        self.value = value

    def _get_hash_recursive(parents):
        return 0x8496f4a66b004f42
    _get_hash_recursive=staticmethod(_get_hash_recursive)
    def _get_packed_fingerprint():
        return CommandType._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def encode(self):
        return struct.pack(">Qi", 0x8496f4a66b004f42, self.value)
    def _encode_one(self, buf):
        buf.write (struct.pack(">i", self.value))

    def decode(data):
        if hasattr (data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != CommandType._packed_fingerprint:
            raise ValueError("Decode error")
        return CommandType(struct.unpack(">i", buf.read(4))[0])
    decode = staticmethod(decode)
    def _decode_one(buf):
        return CommandType(struct.unpack(">i", buf.read(4))[0])
    _decode_one = staticmethod(_decode_one)

