"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class keyboard_command_t(object):
    __slots__ = ["timestamp", "record_type", "save_path", "is_model", "tag"]

    __typenames__ = ["int64_t", "int32_t", "string", "boolean", "int32_t"]

    __dimensions__ = [None, None, None, None, None]

    def __init__(self):
        self.timestamp = 0
        self.record_type = 0
        self.save_path = ""
        self.is_model = False
        self.tag = 0

    def encode(self):
        buf = BytesIO()
        buf.write(keyboard_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.timestamp, self.record_type))
        __save_path_encoded = self.save_path.encode('utf-8')
        buf.write(struct.pack('>I', len(__save_path_encoded)+1))
        buf.write(__save_path_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">bi", self.is_model, self.tag))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != keyboard_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return keyboard_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = keyboard_command_t()
        self.timestamp, self.record_type = struct.unpack(">qi", buf.read(12))
        __save_path_len = struct.unpack('>I', buf.read(4))[0]
        self.save_path = buf.read(__save_path_len)[:-1].decode('utf-8', 'replace')
        self.is_model = bool(struct.unpack('b', buf.read(1))[0])
        self.tag = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if keyboard_command_t in parents: return 0
        tmphash = (0x41fffac871d485bf) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if keyboard_command_t._packed_fingerprint is None:
            keyboard_command_t._packed_fingerprint = struct.pack(">Q", keyboard_command_t._get_hash_recursive([]))
        return keyboard_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", keyboard_command_t._get_packed_fingerprint())[0]

